# SwiftLint Configuration for Routine Chart iOS

# Paths to include/exclude
included:
  - RoutineChart/RoutineChart

excluded:
  - Pods
  - RoutineChart/RoutineChartTests
  - RoutineChart/RoutineChartUITests
  - RoutineChart/RoutineChart.xcodeproj

# Rules
disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rule Configuration
line_length:
  warning: 120
  error: 150
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - db
    - vm
    - vc

force_cast: error
force_try: error
force_unwrapping: warning

# Custom Rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\("
    message: "Use Logger instead of print()"
    severity: warning

